import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import type { EnrichedRecommendation } from "@/lib/scoreMeta";
import type { ScoreSnapshot } from "@/lib/scoreHistory";
import type { MaintenanceItem, Document } from "@/context/HomeWiseContext";
import { normalizeDateForDatabase } from "@/lib/dateForDatabase";

export type MonthlyReportData = {
  propertyAddress: string;
  monthLabel: string;
  overallScore: number;
  completionPercent: number;
  trend: "up" | "down" | "flat";
  trendDelta: number;
  completedTasks: number;
  upcomingTasks: number;
  newDocuments: number;
  recommendations: EnrichedRecommendation[];
  history: ScoreSnapshot[];
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildMonthlyReportData(params: {
  propertyAddress: string;
  overallScore: number;
  completionPercent: number;
  maintenance: MaintenanceItem[];
  documents: Document[];
  recommendations: EnrichedRecommendation[];
  history: ScoreSnapshot[];
}): MonthlyReportData {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const monthLabel = now.toLocaleDateString(undefined, { month: "long", year: "numeric" });

  const completedTasks = params.maintenance.filter((m) => {
    if (m.status !== "Completed" || !m.lastCompleted) return false;
    const completed = normalizeDateForDatabase(m.lastCompleted);
    return completed.ok && completed.iso ? new Date(completed.iso) >= monthStart : false;
  }).length;

  const upcomingTasks = params.maintenance.filter(
    (m) => m.status === "Due Soon" || m.status === "Upcoming"
  ).length;

  // uploadDate is stored as ISO YYYY-MM-DD — match on the year-month prefix.
  const monthPrefix = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const newDocuments = params.documents.filter((d) => {
    const uploaded = normalizeDateForDatabase(d.uploadDate);
    return uploaded.ok && Boolean(uploaded.iso?.startsWith(monthPrefix));
  }).length;

  let trend: "up" | "down" | "flat" = "flat";
  let trendDelta = 0;
  if (params.history.length >= 2) {
    const first = params.history[0].overall;
    const last = params.history[params.history.length - 1].overall;
    trendDelta = last - first;
    if (trendDelta > 1) trend = "up";
    else if (trendDelta < -1) trend = "down";
  }

  return {
    propertyAddress: params.propertyAddress,
    monthLabel,
    overallScore: params.overallScore,
    completionPercent: params.completionPercent,
    trend,
    trendDelta,
    completedTasks,
    upcomingTasks,
    newDocuments,
    recommendations: params.recommendations.slice(0, 8),
    history: params.history,
  };
}

export function buildMonthlyReportHtml(data: MonthlyReportData): string {
  const trendLabel =
    data.trend === "up"
      ? `Improving (+${data.trendDelta})`
      : data.trend === "down"
        ? `Declining (${data.trendDelta})`
        : "Stable";

  const recRows = data.recommendations
    .map(
      (r) =>
        `<tr><td>${escapeHtml(r.label)}</td><td>+${r.points}</td><td>${escapeHtml(r.priority)}</td><td>${escapeHtml(r.estimatedTime)}</td></tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<style>
  body { font-family: -apple-system, sans-serif; color: #0F1F3D; padding: 32px; }
  h1 { color: #1A3C8F; font-size: 22px; }
  .stat { display: inline-block; margin: 8px 16px 8px 0; }
  .stat b { font-size: 28px; color: #1A3C8F; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td { border: 1px solid #DDE3F0; padding: 8px; text-align: left; font-size: 13px; }
  th { background: #EEF2FF; }
  .footer { margin-top: 32px; color: #8A9AB8; font-size: 11px; }
</style></head><body>
<h1>Property Journal Monthly Home Health Report</h1>
<p><strong>${escapeHtml(data.propertyAddress)}</strong> · ${escapeHtml(data.monthLabel)}</p>
<div class="stat"><b>${data.overallScore}</b><br/>Health Score</div>
<div class="stat"><b>${data.completionPercent}%</b><br/>Completion</div>
<div class="stat"><b>${trendLabel}</b><br/>Trend</div>
<div class="stat"><b>${data.completedTasks}</b><br/>Tasks Done</div>
<div class="stat"><b>${data.upcomingTasks}</b><br/>Upcoming</div>
<div class="stat"><b>${data.newDocuments}</b><br/>New Docs</div>
<h2>Priority Recommendations</h2>
<table><tr><th>Action</th><th>Points</th><th>Priority</th><th>Time</th></tr>
${recRows || "<tr><td colspan='4'>No outstanding recommendations.</td></tr>"}
</table>
<p class="footer">Generated by Property Journal · Home Health Score™</p>
</body></html>`;
}

export async function generateMonthlyReportPdf(
  data: MonthlyReportData
): Promise<{ uri?: string; html?: string; error?: string }> {
  try {
    const html = buildMonthlyReportHtml(data);
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    return { uri, html };
  } catch (e: unknown) {
    return { error: e instanceof Error ? e.message : "PDF generation failed" };
  }
}

export async function shareMonthlyReportPdf(uri: string, address: string): Promise<{ error?: string }> {
  try {
    const available = await Sharing.isAvailableAsync();
    if (!available) return { error: "Sharing is not available on this device." };
    const safe = address.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 40);
    const dest = `${FileSystem.cacheDirectory}PropertyJournal_Monthly_${safe}.pdf`;
    await FileSystem.copyAsync({ from: uri, to: dest });
    await Sharing.shareAsync(dest, {
      mimeType: "application/pdf",
      dialogTitle: "Share Monthly Home Health Report",
    });
    return {};
  } catch (e: unknown) {
    return { error: e instanceof Error ? e.message : "Share failed" };
  }
}
